export const relayCompanionCopy = {
  labels: {
    online: 'Online',
    checking: 'Checking',
    offline: 'Offline',
    connected: 'Connected',
    manifestFallback: 'Manifest fallback',
    readOnly: 'Read-only',
  },
  dashboard: {
    assistantSubtitle: 'Cockpit companion for local routing, status, and safe control.',
    popoutButton: 'Open Relay Companion',
    popoutBlocked: 'Popup blocked — launch companion here',
    commandDescription: 'Copy-safe references for running the local cockpit.',
    commandBadge: 'Copy-safe',
    commandTerminalDescription: 'Reference strip only — Relay is not executing shell from the browser.',
    terminalLock: 'EXECUTION LOCKED — REFERENCE MODE ONLY',
    footerLeft: 'Relay cockpit // OpenClaw engine',
    footerRight: 'Read-only bridge // Execution stays locked',
  },
  popout: {
    waiting: 'Standing by for Relay activity.',
    responding: 'Relay is routing a live response.',
    bridgeLinked: 'Read-only engine link is stable.',
    bridgeFallback: 'Manifest fallback is loaded and safe.',
    safety: 'Execution stays locked behind the cockpit glass.',
    voiceDisabled: 'Voice is cold until you arm it.',
    voiceDisabledDetail: 'Manual only. No autoplay.',
    voiceReady: 'Voice lane is armed for a manual check.',
    voiceReadyDetail: 'One click, one local playback. No extra drama.',
    voiceUnavailable: 'Voice backend is off the line.',
    voiceUnavailableDetail: 'Local synthesis is not ready.',
    eventDisabled: (category: string) => `${category} event gate is off.`,
    eventDisabledDetail: 'Flip the matching gate before you ask for that stunt.',
    noEventSelected: 'No event route selected.',
    startupHint: 'Startup only runs from Voice On when the startup gate is armed.',
    eventHint: 'Manual test stays manual. Pick routing, success, or warning for an event run.',
    generating: (category: string) => `Building ${category} line...`,
    playing: (category: string) => `${category} line live.`,
    manualPlaying: 'Manual playback is in motion.',
    eventPlaying: 'Gated event playback is in motion.',
    playbackComplete: 'Playback complete. No casualties.',
    playbackReplay: (category: string) => `Manual only. Run ${category} again if you want another pass.`,
    eventReplay: (category: string) => `Event pass complete. Trigger ${category} again only if you mean it.`,
    playbackFailed: 'Playback failed.',
    playbackFailedDetail: 'Browser playback dropped the handoff.',
    refreshingStatus: 'Refreshing Relay status...',
    refreshingStatusDetail: 'Checking backend health and bridge readiness.',
    refreshSuccess: 'Relay status refreshed. Systems behaving.',
    refreshSuccessDetail: 'Backend online. Bridge linked. No surprises.',
    refreshAttention: 'Relay status needs attention.',
    refreshFallbackDetail: 'Backend is up, but the bridge fell back to manifest mode.',
    refreshOfflineDetail: 'Backend is off the line. Check local services.',
    refreshFailed: 'Relay status refresh failed.',
    statusReady: (category: string) => `${category} lane ready.`,
    statusReadyVariant: (count: number) => `${count} variants loaded. Relay will pick one per manual run.`,
    statusReadySingle: 'Manual only. One click gives one local playback.',
    variantNote: 'Variant selected on each manual playback',
    voiceBehaviorNote: 'Voice stays off by default and plays only on user-triggered actions.',
    gateNote: 'Category preview stays silent. Use Voice On, Run Selected Event, or Refresh Relay Status for deliberate reactions.',
    runSelectedEvent: 'Run Selected Event',
    refreshStatus: 'Refresh Relay Status',
    refreshingShort: 'Refreshing...',
    playTestLine: 'Play test line',
  },
  layout: {
    backendOffline: 'Relay lost the backend line.',
    backendOfflineAction: 'Check Relay URL',
  },
} as const;
